# GitHub Actions 上での名前
name: BuildActionToNetlify

# 起動条件
on:
  workflow_dispatch: # GithubActions上で実行ボタンを表示
  # schedule:
  #   - cron: "*/30 * * * *" # 30分毎に実行：https://crontab.guru/#*/30_*_*_*_*
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: |
          echo "::group::Deploy to Netlify"
          # ルートディレクトリから直接デプロイ
          for i in {1..3}; do
            netlify deploy --dir . --prod > cli.txt && break || sleep 60
          done
          # Extract URLs from cli.txt
          URLS=$(sed -n '/Build logs:/,$p' cli.txt)
          # Extract the rest of the log
          LOG=$(sed '/Build logs:/Q' cli.txt)
          echo "<details><summary>Netlify Build Log</summary>"
          echo "```"
          echo "$LOG"
          echo "```"
          echo "</details>"
          echo "$URLS"
          echo "::endgroup::"
        env:
          NETLIFY_SITE_ID   : ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN_REDIRECT: ${{ secrets.NETLIFY_AUTH_TOKEN_REDIRECT }}
